Added Voici notes as they stand
Jupyter4Science/scipy2024-jupyter-widgets-tutorial pull request #15
Opened 2024-06-21 15:30 UTC by JuanCab

I had some challenges getting `voici build` running (and I don't believe it is producing proper output yet).  I have placed them online for now in this draft PR so you all can see if your luck is better than mine.

2024-06-24 19:03 UTC, JuanCab commented
I revised the `voici` instructions.  Note this required changing the `environment.yml` to add `micromamba` which is currently the only reliable build tool for voici.  Its a fairly short writeup, so I would appreciate any feedback.

2024-06-25 18:25 UTC, mwcraig requested changes
Only one important change: drop `widgets_pydantic.py` from the `dashboard` folder.

I know there are some typos in the updates, and it might make sense to rename the notebook so that it just covers voici, but those are changes @nicole-brewer and I can make while you are gone.

I will try out the install/build instructions in a few minutes.

2024-06-25 18:27 UTC, mwcraig commented
Also, I'd like to get #8 in before we merge this or there will be a bunch of conflicts.

2024-06-25 18:44 UTC, mwcraig commented on 04b_deployment_clientside.ipynb
> +    "At this point you can test and see if the web application works by running a local web server pointed at the `_output` directory and then openning a new browser tab pointed at the local server [
```suggestion
    "At this point you can test and see if the web application works by running a local web server pointed at the `_output` directory and then opening a new browser tab pointed at the local server [(**http://localhost:8000/**)](http://localhost:8000/).  If it works, you can deploy the `_output` directory to a web server. If you execute the following cell, you will need to \"Interrupt\" the kernel to continue with the rest of the notebook."
```

2024-06-25 18:50 UTC, mwcraig commented
One last comment for now -- the fix in #8 in `key/dashboard/widgets.py` (which will get picked up once #8 is in and this is rebased) is necessary for the dashboard to work.

2024-06-25 20:08 UTC, JuanCab commented
> One last comment for now -- the fix in #8 in `key/dashboard/widgets.py` (which will get picked up once #8 is in and this is rebased) is necessary for the dashboard to work.

Went ahead and rebased this branch to the current `widgets-tweaks` branch.

2024-06-26 01:32 UTC, mwcraig commented
Can you try rebasing on main? If you prefer I can give that a go, still have about an hour of working time tonight until we get to our hotel.

2024-06-26 01:50 UTC, JuanCab commented
> Can you try rebasing on main? If you prefer I can give that a go, still have about an hour of working time tonight until we get to our hotel.

Rebased onto current main (a lot of conflict resolution involved, bleh).

2024-06-26 14:39 UTC, closed without merging